### ISSUE TITLE
saveig.app is now savevid.net

### ISSUE THREAD

**Issue by psndsysops** [victorsouzaleal/instagram-direct-url#16]

**Comment by psndsysops** [comment]
I made a mistake in my text, that is not an error, that is a correct output, but it's missing links to video that i am trying to download.

So while { results_number: 0, url_list: [] } is valid and not an error, it's still a mistake and not at all what should be given back from the api

**Comment by victorsouzaleal** [comment]
hey thanks for letting me know, it's updated now.
