### ISSUE TITLE
Results Occasionally Contain `undefined`

### ISSUE THREAD

**Issue by beanc16** [victorsouzaleal/instagram-direct-url#18]
When attempting to download videos, sometimes the response payload from the api under-the-hood is as follows:
```json
{
  "video": [
    { // Note that this only has a thumbnail with no video url
      "thumbnail": "someUrl`"
    },
    {
      "video": "someUrl2",
      "thumbnail": "someUrl3"
    }
  ],
  "image": [
    "someUrl4"
  ],
  "fetch": true
}
```

When an object in the `video` has only a thumbnail but no video, this package outputs an array with `undefined` in it:
```json
[
  undefined,
  "someUrl2",
  "someUrl4"
]
```

This should probably be updated to handle this use case such that this array never contains `undefined`.

**Comment by victorsouzaleal** [comment]
Gotcha, i updated it and now if there is no video link it will send the thumbnail instead of 'undefined'. Thanks :+1:
