### ISSUE TITLE
Not Working!!!

### ISSUE THREAD

**Issue by codingstark-dev** [victorsouzaleal/instagram-direct-url#2]
This script is not working I think because every time I run the script I get only empty arrays `{ results_number: 0, url_list: [] }`

**Comment by victorsouzaleal** [comment]
Send the instagram link for me to test

**Comment by victorsouzaleal** [comment]
![image](https://user-images.githubusercontent.com/4674786/119752704-da6c9e00-be73-11eb-81e7-984bbb86845e.png)
Working here, check if your link is a valid url. 
ex : https://www.instagram.com/p/xxxxxxxxxxxx/

**Comment by refoxdev** [comment]
> Send the instagram link for me to test

https://www.instagram.com/p/CL6NT19JqDR/

**Comment by victorsouzaleal** [comment]
![image](https://user-images.githubusercontent.com/4674786/119851764-10963600-bee5-11eb-95eb-641df741bb4c.png)
Working

**Comment by viditagarwal10** [comment]
Same problem is coming when I am using this script in heroku node server. Although, When I use it in local server It works fine. Looks like a "CORS" problem. My best guess.\

**Comment by refoxdev** [comment]
> Same problem is coming when I am using this script in heroku node server. Although, When I use it in local server It works fine. Looks like a "CORS" problem. My best guess.\

ya same !! Instagram getting more and more strict
