### ISSUE TITLE
Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by vitor-zanatta-walter** [victorsouzaleal/instagram-direct-url#22]
![{A1DD8828-FA32-42B0-AA5B-B284106C178A}](https://github.com/user-attachments/assets/3bd400f5-5f7e-4c17-a1e8-dbc8d4b762e6)

exemplo de link: https://www.instagram.com/reel/DAOkYRuPRhz/?igsh=aHM0amQ5eG8zbHNp

**Comment by victorsouzaleal** [comment]
Verifique se está funcionando na mesma versão

**Comment by vitor-zanatta-walter** [comment]
aparentemente tudo funcionando normal depois da atualização, obrigado!
