### ISSUE TITLE
Request failed with status code 500

### ISSUE THREAD

**Issue by vitor-zanatta-walter** [victorsouzaleal/instagram-direct-url#24]
![{BB4427F8-4AD6-4E4D-A2EE-046B0FDE6436}](https://github.com/user-attachments/assets/4a7687d1-0a74-417f-96b7-fc1af113ff5f)

Link de exemplo: https://www.instagram.com/reel/DBgdg8duFRe/?igsh=MWlzOXliNWVmbWd4Yg%3D%3D

**Comment by burstw0w** [comment]
Yeah, i do get similar stuff.

data: { error: 'Failed to fetch Instagram embed data' }
status: 500 

It's been working sometimes tho, so maybe it's some kind of rate limit?

**Comment by victorsouzaleal** [comment]
Try again new latest version

**Comment by burstw0w** [comment]
It might work, but isn't Rapid API pay2use? 

Wouldn't this be just a short term solution?

**Comment by victorsouzaleal** [comment]
> It might work, but isn't Rapid API pay2use?
> 
> Wouldn't this be just a short term solution?

I got it from a site that left the key exposed, as long as it's working I don't care xD

**Comment by r0hin** [comment]
Seems a short term solution then 💀

**Comment by burstw0w** [comment]
> > It might work, but isn't Rapid API pay2use?
> > Wouldn't this be just a short term solution?
> 
> I got it from a site that left the key exposed, as long as it's working I don't care xD

Maybe we can find a more permanent solution, or even try to grab direct URL's directly instead of using API?

I managed to get out videos from instagram, but i never managed to get audio working. So i do have a way to pull out a video out of link, but it won't have audio which sucks

**Comment by victorsouzaleal** [comment]
> Seems a short term solution then 💀

All solutions are not permanent, many stop working or the site uses some protection... Enjoy it while it works.

**Comment by victorsouzaleal** [comment]
I made a change to get the information directly from Instagram, check if everything is ok.

**Comment by r0hin** [comment]
works for me!

**Comment by burstw0w** [comment]
Great, everything works much faster and this seems to be more permanent solution, the only thing that is not working is stories.

I had same issue with all instagram story links:

TypeError: Cannot read properties of null (reading 'edge_sidecar_to_children')

**Comment by burstw0w** [comment]
i might try and fix that tho, tonight (European time)

**Comment by victorsouzaleal** [comment]
> Great, everything works much faster and this seems to be more permanent solution, the only thing that is not working is stories.
> 
> I had same issue with all instagram story links:
> 
> TypeError: Cannot read properties of null (reading 'edge_sidecar_to_children')

Send me a story link example, I never used it to download story.

**Comment by burstw0w** [comment]
@victorsouzaleal well, the stories will just dissapear after a while, but here it is:

https://www.instagram.com/stories/fabriziorom/3493525039488177455/

This is a random profile with bunch of stories, so you can test it

**Comment by victorsouzaleal** [comment]
> @victorsouzaleal well, the stories will just dissapear after a while, but here it is:
> 
> https://www.instagram.com/stories/fabriziorom/3493525039488177455/
> 
> This is a random profile with bunch of stories, so you can test it

Yes, I don't think it's viable... The objective of the project is to get download links from posts, the stories is more for projects like "Profile downloader" .
