### ISSUE TITLE
Formato de link sem suporte

### ISSUE THREAD

**Issue by vitor-zanatta-walter** [victorsouzaleal/instagram-direct-url#27]
Você poderia adicionar suporte a reels do instagram com links nesse formato?

https://www.instagram.com/share/reel/BAPa6ljOT

https://www.instagram.com/share/reel/BBssG7qOOw

**Comment by victorsouzaleal** [comment]
Adicionei o suporte, mas o seu primeiro link não é valido ele redireciona pra um video aleatorio... Adicionei também suporte a "reels" :+1:
