### ISSUE TITLE
Reels downloader not working 

### ISSUE THREAD

**Issue by Lawny61** [victorsouzaleal/instagram-direct-url#4]
The reel downloader send thumbnail instead of videos please could you check on this

**Comment by divyeshdobariya** [comment]
Working fine till yesterday , but now it's not working, can you please update the package , thanks for your great support.

**Comment by Lawny61** [comment]
> Working fine till yesterday , but now it's not working, can you please update the package , thanks for your great support.

It's working if you have are having a problem it's because your IP address have been restricted

**Comment by divyeshdobariya** [comment]
I tried with different ip , but still not working , is there any solution for that ?

**Comment by Lawny61** [comment]
The issue is your ip is static it can be restricted if you make many calls . The solution is to create an api using express and instagram url direct and host it in google cloud (No static ip) .

**Comment by divyeshdobariya** [comment]
Thanks for your support, can you please tell me how to configure that, if you can suggest, then it will great help for me , Thanks...

**Comment by Lawny61** [comment]
Have you ever used firebase cloud host?

**Comment by ardhityawiedhairawan** [comment]
This problem also happened to me. After trying to find out, this problem is because the function failed to access the url https://instasupersave.com. I have tried moving to another server (a different IP address), but it still doesn't work.

Still figuring out how to solve this problem.

**Comment by Lawny61** [comment]
> This problem also happened to me. After trying to find out, this problem is because the function failed to access the url https://instasupersave.com. I have tried moving to another server (a different IP address), but it still doesn't work.
> 
> Still figuring out how to solve this problem.

It's working fine for me try to reinstall the package npm and then give it another try

**Comment by divyeshdobariya** [comment]
ok , let me try , thanks for your great support !!

**Comment by ardhityawiedhairawan** [comment]
I've tried moving to another IP, but the "Request failed with status code 403" problem still occurs to me.
