### ISSUE TITLE
instagram story sometime even video giving images 

### ISSUE THREAD

**Issue by aliraees123** [victorsouzaleal/instagram-direct-url#5]
Can u fix the issue please today its story video first sometime gives image and sometime its not running when put in html video tag or any react Tag can u fix these issues will be really appreciated cuz there is no package just like this its amazing work thanks in advance

**Comment by victorsouzaleal** [comment]
Send me link examples that you are facing these problems so I can analyze what is happening

**Comment by aliraees123** [comment]
ok

**Comment by aliraees123** [comment]
https://instadownloader-next-k4aa.vercel.app/en this is the link suppose u
enter the user name of the story that has only one story if it will be
video then it will give the image link its just only one issue now other
issue as they are  solved now
